name: Epic
description: Tracks a large body of work broken into smaller tasks.
labels: ["Epic"]
type: Epic
body: 
  - type: textarea
    attributes:
      label: Description
      description: Describe the business objective and impact.
    validations:
      required: true
  - type: dropdown
    id: business_area
    attributes:
      label: Business Area
      description: Business Area
      options:
        - Sanbox
        - Artificial Intelligence
        - Document Management
      default: 0
